---

site_domains:
  - "{{ ansible_env.SITE_DOMAIN }}"

site_domain: "{{ site_domains[0] }}"

site_root: "/var/www/vhosts/{{ site_domain }}"

elasticsearch_name: "elasticsearch5"

magento_crypt_key: 4ac4e9840846688730baaf4157d50ee8

copy_nginx_certs: false

magento_theme: "Magento/backend SomethingDigital/bryantpark"

magento_repo_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62306432363434363539623734396131613833333266366238636135636231346539656464336564
  3035663632616435383364393435613833323332313262640a623664316331376236616534323833
  30643162373538646333303734346265666234363535656363663337366663336362396462616164
  6464383037616238340a326263656232613164653830656337653535333363646436623034383835
  66356632303439653933326132356361666137356463323566336433376634336438616430386132
  6432353232316638353834356530663532383861306133633733

magento_repo_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31376461393764333834313036663335356661643865616166306162313839343664633662373332
  3964643436333738363965316464666165343132666231620a336131613266623031306362323737
  34393763643134653664393234333862333862336462353738376162633261323631656661396361
  6166663462383438650a303966346538313138336233363439383435333333613138306162396532
  65356334643565666439333834343836666631333437643564363939363835636231303263366464
  6131626466366165343661616134643465626564313539326637
